language: python
cache: pip

python:
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install .[dev]

script:
    - cd tests
    - py.test --no-plot-compare

jobs:
  include:
    - stage: compliance
      script: pre-commit run --all-files

stages:
  - compliance
  - test
